---

- name: Install fluentd_extra_packages
  yum:
    name: "{{ fluentd_extra_packages }}"
    state: present

- name: Install fluentd
  yum:
    name: "{{ fluentd_package_name }}"
    state: present

- name: Install openssl
  yum:
    name: openssl
    state: present
